version: '3.1'
services:
  db:
    image: mysql
    container_name: mydb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DB_NAME: DB_myfinances
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: root
      MYSQL_HOST: localhost
    ports:
      - 3306:3306
volumes:
  mysqldata:
